name: telegram_notify

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom telegram message
        uses: F2had/pr-telegram-action@v1.0.0
        with:
          bot_token: "${{ secrets.BotToken }}"
          chat_id: "${{ secrets.CHATID }}"
